roles:
  data:
    user:
      id: user
      role: user
      description: Normal Role
    admin:
      id: admin
      role: admin
      internalRoles:
        - user
        - developer
      description: All the access of the Application
    developer:
      id: developer
      role: developer
      internalRoles:
        - user
      description: Developer Role
    tester:
      id: tester
      role: tester
      internalRoles:
          - user
      description: Tester Role