server:
  port: ${SERVER_PORT:7001}
  shutdown: graceful
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    max-connections: 10000
    accept-count: 100
    connection-timeout: 5000
    max-http-form-post-size: 2MB
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain,text/css,application/javascript
    min-response-size: 2048
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-message: never
  forward-headers-strategy: framework
spring:
  servlet:
    multipart:
      max-file-size: 100MB
  application:
    name: revquix-backend
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5437}/${POSTGRES_DB:revquix}
    hikari:
      username: ${PG_USER:revquix}
      password: ${PG_PASSWORD:revquix123!}
      maximum-pool-size: 100
      minimum-idle: 7
      leak-detection-threshold: 120000
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      auto-commit: false
      # Additional properties to handle network disconnection issues
      validation-timeout: 3000
      keepalive-time: 30000
      initialization-fail-timeout: 1
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    out-of-order: false
    placeholder-replacement: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis123!}
      username: ${REDIS_USERNAME:default}
      database: 0
      connect-timeout: 2000ms
      timeout: 2000ms
      ttl: 3600
      lettuce:
        pool:
          max-active: 50
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms

rate-limiting:
  enabled: true
  ip-rate-limit:
    enabled: true
    request-per-minute: 60
    request-per-hour: 2000
    blocked-duration-minutes: 15

auth:
  key-data:
    alias: ${KEY_ALIAS:revquix}
    password: ${KEY_PASSWORD:Revquix@1234}
    path: /keys/revquix.p12
  cors:
    allow-credentials: true
    max-age: 3600
    allowed-origins:
      - http://localhost:2000
      - https://revquix.com
  info:
    access-token-expiry-minutes: 20
    refresh-token-expiry-days: 30
    refresh-token-cookie-name: revquix-refresh-token
    is-production: true
    is-remote-address-authentication: true
    is-refresh-token-authentication: true
  exclude-paths:
    paths:
      - /v1/auth/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-ui.html
      - /actuator/**
  otp-info:
    registration:
      log-enabled: true
      otp-expiry-minutes: 10
      mail-enabled: true
      max-otp-requests: 4
    password-reset:
      log-enabled: true
      otp-expiry-minutes: 10
      mail-enabled: true
      max-otp-requests: 4
  authorization:
    roles-to-allow:
      local:
        instance: local
        must-roles:
          - user
      dev:
        instance: dev
        must-roles:
          - user
          - developer
          - tester
      production:
        instance: production
        must-roles:
          - user

swagger:
  group-name:
    definition: ${spring.application.name}
    scan-packages: com.revquix.backend
  info:
    title: Revquix Backend
    version: v1
    description: API Documentation for Revquix Backend Application
    summary: The Revquix SM Application is a comprehensive blog platform integrated with advanced social media features, enabling users to create, share, and interact with content seamlessly. Built with Java 17 and Spring Boot, it supports blogging, user profiles, comments, likes, real-time notifications, and social sharing for an engaging community experience.
    contact:
      name: Revquix
      email: support@revquix.com
      url: https://www.revquix.com
    license:
      name: Apache 2 License
      url: https://github.com/Revquix/revquix-backend/LICENSE
  servers:
    local:
      name: Local Port
      url: http://localhost:7001

async:
  executor:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 100
    keep-alive-seconds: 60
    await-termination-seconds: 20
    thread-name-prefix: revquix-async-

logging:
  level:
    com.revquix.backend: DEBUG